# **SpaceX  Falcon 9 First Stage Landing Prediction**

Note: This project utilizes a set of utility functions provided by IBM (e.g., get...Data, plot_confusion_matrix) to streamline data acquisition and visualization. All subsequent analysis, hyperparameter tuning, and model evaluation were performed independently.

# Interactive Visual Analytics with Folium

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

Let's first import required Python packages for this lab:

In [ ]:
!pip install pandas folium

Collecting folium
  Downloading folium-0.20.0-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting branca>=0.6.0 (from folium)
  Downloading branca-0.8.2-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: jinja2>=2.9 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from folium) (3.1.6)
Requirement already satisfied: numpy in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from folium) (2.3.0)
Requirement already satisfied: requests in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from folium) (2.32.4)
Collecting xyzservices (from folium)
  Downloading xyzservices-2026.3.0-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2>=2.9->folium) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->folium) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->folium) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->folium) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in C:\Users\Rostyslav Kharevych\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests->folium) (2025.4.26)
Downloading folium-0.20.0-py2.py3-none-any.whl (113 kB)
Downloading branca-0.8.2-py3-none-any.whl (26 kB)
Downloading xyzservices-2026.3.0-py3-none-any.whl (94 kB)
Installing collected packages: xyzservices, branca, folium

   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   -------------------------- ------------- 2/3 [folium]
   ---------------------------------------- 3/3 [folium]

Successfully installed branca-0.8.2 folium-0.20.0 xyzservices-2026.3.0

In [4]:
import folium
import pandas as pd

In [5]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

## Let's mark all launch sites on a map

First, let's add each site's location on a map using site's latitude and longitude coordinates

The following dataset with the name `spacex_launch_geo.csv` is an augmented dataset with latitude and longitude added for each site.

In [11]:
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'
spacex_df=pd.read_csv(URL)

Now, take a look at what are the coordinates for each site.

In [12]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give us any intuitive insights about where are those launch sites. Let's visualize those locations by pinning them on a map.

We first need to create a folium `Map` object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [13]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

We could use `folium.Circle` to add a highlighted circle area with a text label on a specific coordinate.

In [14]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and we can find a small yellow circle near the city of Houston and we can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame `launch_sites`

In [15]:
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

In [22]:
# Initialize the map centered around NASA coordinates
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)

# Define the coordinates for each launch site
ccafs_lc = [28.562302, -80.577356]
ccafs_slc = [28.563197, -80.576820]
ksc_lc = [28.573255, -80.646895]
vafb_slc = [34.632834, -120.610745]

# Create an orange circle at CCAFS LC-40's coordinate with a popup label showing its name
circle1 = folium.Circle(ccafs_lc, radius = 1000, color = '#d35400', fill=True).add_child(folium.Popup('CCAFS LC-40'))
# Create an orange circle at CCAFS SLC-40's coordinate with a popup label showing its name
circle2 = folium.Circle(ccafs_slc, radius = 1000, color = '#d35400', fill=True).add_child(folium.Popup('CCAFS SLC-40'))
# Create an orange circle at KSC LC-39A's coordinate with a popup label showing its name
circle3 = folium.Circle(ksc_lc, radius = 1000, color = '#d35400', fill=True).add_child(folium.Popup('KSC LC-39A'))
# Create an orange circle at VAFB SLC-4E's coordinate with a popup label showing its name
circle4 = folium.Circle(vafb_slc, radius = 1000, color = '#d35400', fill=True).add_child(folium.Popup('VAFB SLC-4E'))

# Create a marker at CCAFS LC-40's coordinate with a text label showing its name
marker1 = folium.map.Marker(
    ccafs_lc,
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40',
    )
)
# Create a marker at CCAFS SLC-40's coordinate with a text label showing its name
marker2 = folium.map.Marker(
    ccafs_slc,
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40',
    )
)
# Create a marker at KSC LC-39A's coordinate with a text label showing its name
marker3 = folium.map.Marker(
    ksc_lc,
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A',
    )
)
# Create a marker at VAFB SLC-4E's coordinate with a text label showing its name
marker4 = folium.map.Marker(
    vafb_slc,
    icon = DivIcon(
        icon_size = (20,20),
        icon_anchor = (0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E',
    )
)

# Add all circles and markers to the map
site_map.add_child(circle1)
site_map.add_child(marker1)
site_map.add_child(circle2)
site_map.add_child(marker2)
site_map.add_child(circle3)
site_map.add_child(marker3)
site_map.add_child(circle4)
site_map.add_child(marker4)

## Key Findings & Site Analysis:
* Coastline Optimization: All sites (CCAFS, KSC, VAFB) are strategically located adjacent to the ocean. This allows for a safe "eastward" flight path over water, minimizing risk to populated areas during launch and stage separation.
* Logistical Infrastructure: Visual analysis confirms that each site is positioned near major railways and highways, essential for transporting heavy booster stages and payload fairings.
* Safety Buffers: The use of Folium's Circle feature highlights the required safety exclusion zones around each pad, demonstrating the scale of the facility needed for Falcon 9 operations.

## Let's mark the success/failed launches for each site on the map

Next, let's try to enhance the map by adding the launch outcomes for each site, and see which sites have high success rates.

In [18]:
spacex_df.tail(10)

     Launch Site        Lat       Long  class
46    KSC LC-39A  28.573255 -80.646895      1
47    KSC LC-39A  28.573255 -80.646895      1
48    KSC LC-39A  28.573255 -80.646895      1
49  CCAFS SLC-40  28.563197 -80.576820      1
50  CCAFS SLC-40  28.563197 -80.576820      1
51  CCAFS SLC-40  28.563197 -80.576820      0
52  CCAFS SLC-40  28.563197 -80.576820      0
53  CCAFS SLC-40  28.563197 -80.576820      0
54  CCAFS SLC-40  28.563197 -80.576820      1
55  CCAFS SLC-40  28.563197 -80.576820      0

Next, let's create markers for all launch records.
If a launch was successful `(class=1)`, then we use a green marker and if a launch was failed, we use a red marker `(class=0)`

Note that a launch only happens in one of the four launch sites, which means many launch records will have the exact same coordinate. Marker clusters can be a good way to simplify a map containing many markers having the same coordinate.

Let's first create a `MarkerCluster` object

In [19]:
marker_cluster = MarkerCluster()

In [20]:
spacex_df['marker_color'] = ['green' if x == 1 else 'red' for x in spacex_df['class']]
# Apply a function to check the value of `class` column
# If class=1, marker_color value will be green
# If class=0, marker_color value will be red

In [23]:
# Add the marker cluster to the site map to group launch markers together
site_map.add_child(marker_cluster)

# Iterate through each launch record in the SpaceX dataframe to create markers
for index, record in spacex_df.iterrows():
    # Define the coordinate for the specific launch using its Latitude and Longitude
    coordinate = [record['Lat'], record['Long']]
    
    # Create a marker for the launch with a specific color based on the launch outcome
    marker = folium.Marker(
        coordinate,
        icon = folium.Icon(
            color='white', 
            icon_color=record['marker_color']
        )
    )
    
    # Add the newly created marker to the marker cluster
    marker_cluster.add_child(marker)

# Display the updated site map
site_map

From the color-labeled markers in marker clusters, we can easily identify which launch sites have relatively high success rates.

## Let's now calculate the distances between a launch site to its proximities

We need to explore and analyze the proximities of launch sites.

Let's first add a `MousePosition` on the map to get coordinate for a mouse over a point on the map. As such, while we are exploring the map, we can easily find the coordinates of any points of interests (such as railway)

In [25]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)
site_map

This function implements the Haversine formula, which is the standard way to calculate the great-circle distance between two points on a sphere given their longitudes and latitudes.

In [26]:
from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [27]:
# find coordinate of the closet coastline
# e.g.,: Lat: 28.56367  Lon: -80.57163
launch_site_lat = 34.632834	
launch_site_lon = -120.610745
coastline_lat = 34.6339
coastline_lon = - 120.626
distance_coastline = calculate_distance(launch_site_lat, launch_site_lon, coastline_lat, coastline_lon)

In [29]:
# Define the coordinate for the specific point of interest on the coastline
location = [coastline_lat, coastline_lon]

# Create a marker at the coastline coordinate with a text label showing the calculated distance in kilometers
distance_marker = folium.Marker(
    location,
    icon=DivIcon(
        # Set the size and alignment of the text label
        icon_size = (20,20),
        icon_anchor=(0,0),
        # Format the distance value to two decimal places and apply styling to the HTML label
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % "{:10.2f} KM".format(distance_coastline),
    )
)

In [ ]:
locations = [[launch_site_lat, launch_site_lon],[coastline_lat, coastline_lon]]
lines = folium.PolyLine(locations, weight =1)
site_map.add_child(lines)

In [30]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
railway_lat = 34.63334
railway_lon = -120.6396
distance_railway = calculate_distance(launch_site_lat, launch_site_lon, railway_lat, railway_lon)

location = [railway_lat, railway_lon]
distance_marker = folium.Marker(
    location = location,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12px; color:#d35400;"><b>{:10.2f} KM</b></div>'.format(distance_railway),
    )
)

locations = [[launch_site_lat, launch_site_lon], [railway_lat, railway_lon]]
lines = folium.PolyLine(locations, weight = 1)
site_map.add_child(lines)

In [31]:
print(distance_railway)

2.6414332721070246

In [61]:
city_lat = 34.0605
city_lon = -118.26188
distance_city = calculate_distance(launch_site_lat, launch_site_lon, city_lat, city_lon)
location = [city_lat, city_lon]
distance_marker = folium.Marker(
    location = location,
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12px; color:#d35400;"><b>{:10.2f} KM</b></div>'.format(distance_city),
    )
)

locations = [[launch_site_lat, launch_site_lon], [city_lat, city_lon]]
lines = folium.PolyLine(locations, weight = 1)
site_map.add_child(lines)

In [32]:
highway_lat = 34.64168
highway_lon = -120.45753

distance_highway = calculate_distance(launch_site_lat, launch_site_lon, highway_lat, highway_lon)
location = [highway_lat, highway_lon]
distance_marker = folium.Marker(
    location=location,
    icon=DivIcon(
        icon_size=(150, 36),     # Much wider to accommodate "10.25 KM"
        icon_anchor=(0, 0),      # Anchors the top-left of the text to the coordinate
        # Removed the 10 leading spaces (10.2f -> .2f) and added a div width
        html='<div style="font-size: 12px; color:#d35400; width: 150px;"><b>{:.2f} KM</b></div>'.format(distance_highway)
    )
)

locations = [[launch_site_lat, launch_site_lon], [highway_lat, highway_lon]]
lines = folium.PolyLine(locations, weight = 1)
site_map.add_child(lines)

# Key Findings & Logistics:
* Coastline Safety: All pads are positioned within a very short distance (typically <1 km) of the coastline, facilitating immediate eastward flight over the Atlantic or Westward over the Pacific for safety.
* Transportation Efficiency: Proximity to highways and railways is consistently optimized (<2 km) to reduce the logistical risk and cost of transporting oversized booster stages.
* Urban Isolation: Distance measurements confirm that sites are situated far enough from major cities to comply with stringent safety regulations while remaining accessible to technical labor hubs.

<!--## Change Log--!>

<!--| Date (YYYY-MM-DD) | Version | Changed By      | Change Description      |
| ----------------- | ------- | -------------   | ----------------------- |
| 2022-11-09        | 1.0     | Pratiksha Verma | Converted initial version to Jupyterlite|--!>